image: node:6.9

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn

test_installs:
  script:
   - ./tasks/e2e-installs.sh

test_simple:
  script:
   - ./tasks/e2e-simple.sh

test_kitchensink:
  script:
   - ./tasks/e2e-kitchensink.sh
